### ISSUE TITLE
Cant remove title info

### ISSUE THREAD

**Issue by marcabbink** [sharkhack/IOSStatusBarAne#1]
I just tried out your ANE, and all the 4 display options for the header info. But non of the options actually removes the header info. All it does is make it black or white.

Can you add an option that removes all the header info?

**Comment by marcabbink** [comment]
Btw, I'm using the latest Air SDK (4.0) with Flex 4.6)

**Comment by sharkhack** [comment]
Hi,
Do you mean hide StatusBar?

**Comment by marcabbink** [comment]
Yes, hide it completely in IOS7

**Comment by sharkhack** [comment]
would you try? (last commit)

**Comment by marcabbink** [comment]
Yeah, I'm gonne try it.

**Comment by marcabbink** [comment]
Wouw, it works :D! You just made my day;) Tnx
Btw, I know there are a lot of other air developer dealing with this issue. So I will help spreading this.

**Comment by sharkhack** [comment]
Super :)
